image: openjdk:11

stages:
  - build
  - package

build:
  stage: build
  script:
  - ./mvnw clean compile verify
  only:
  - develop


package:
  stage: package
  script:
  - ./mvnw clean package
  artifacts:
    paths:
      - target/geoname-0.0.1-SNAPSHOT.jar
  only:
  - develop
